CREATE TABLE [dbo].[LOP6_KEHOACH] -- Payment Plan
(
	[MAHDTD] [nvarchar](50) NULL, -- Credit Contract ID
	[KY] [int] NULL, -- Term Number
	[DUNOGOC] [numeric](18, 0) NULL, -- Principal Balance
	[NGAYDAUKI] [date] NULL, -- Period Start Date
	[NGAYCUOIKI] [date] NULL, -- Period End Date
	[SONGAYTINHLAI] [int] NULL, -- Interst Caculation Date
	[GOC_PHAITRA] [numeric](18, 0) NULL, -- Principal Due
	[LAI_PHAITRA] [numeric](18, 0) NULL, -- Interest Due
	[TONGTIEN] [numeric](18, 0) NULL -- Total Paymnet
)
---------- Create Produce --------------
-------------------------------------


CREATE OR ALTER proc [dbo].[LOP6_B19_TAOKEHOACH]
	@MAHDTD NVARCHAR(20)
AS
BEGIN
	DELETE FROM LOP6_KEHOACH WHERE MAHDTD = @MAHDTD;
	
	DECLARE @KYHAN INT;
	SET @KYHAN = (SELECT KY_HAN FROM HOPDONG_TINDUNG WHERE MA_HOPDONG_TINDUNG = @MAHDTD);

	DECLARE @LAISUAT NUMERIC(18,2);
	SET @LAISUAT = (SELECT LAISUAT FROM HOPDONG_TINDUNG WHERE MA_HOPDONG_TINDUNG = @MAHDTD);

	DECLARE @SOTIEN NUMERIC(18,2);
	SET @SOTIEN = (SELECT SOTIEN FROM HOPDONG_TINDUNG WHERE MA_HOPDONG_TINDUNG = @MAHDTD);

	DECLARE @NGAY_GN DATE;
	SET @NGAY_GN = (SELECT NGAY_GIAINGAN FROM HOPDONG_TINDUNG WHERE MA_HOPDONG_TINDUNG = @MAHDTD);

	DECLARE @NGAY_DH DATE;
	SET @NGAY_DH = (SELECT NGAY_DAOHAN FROM HOPDONG_TINDUNG WHERE MA_HOPDONG_TINDUNG = @MAHDTD);

	DECLARE @I INT;
	SET @I = 1;
	
	DECLARE @GOCPHAITRA_MOIKY NUMERIC(18,0)
	SET		@GOCPHAITRA_MOIKY = ROUND(@SOTIEN/@KYHAN,0)

	WHILE @I <= @KYHAN
		BEGIN
			INSERT INTO LOP6_KEHOACH VALUES (@MAHDTD, @I, @SOTIEN-(@I-1)*@GOCPHAITRA_MOIKY ,@NGAY_GN, DATEADD(DAY,-1, DATEADD(MONTH,1,@NGAY_GN)), 0, @GOCPHAITRA_MOIKY, 0,0);
			SET @I = @I+1;
			SET @NGAY_GN = DATEADD(MONTH,1,@NGAY_GN)
		END

	UPDATE LOP6_KEHOACH SET NGAYCUOIKI		= @NGAY_DH WHERE KY= @I AND MAHDTD = @MAHDTD;
	UPDATE LOP6_KEHOACH SET SONGAYTINHLAI	= DATEDIFF(DAY,NGAYDAUKI,NGAYCUOIKI) +1 WHERE MAHDTD = @MAHDTD;
	UPDATE LOP6_KEHOACH SET LAI_PHAITRA		= ROUND(SONGAYTINHLAI*@LAISUAT*DUNOGOC/36500,0) WHERE MAHDTD = @MAHDTD;
	UPDATE LOP6_KEHOACH SET TONGTIEN        = GOC_PHAITRA + LAI_PHAITRA WHERE MAHDTD = @MAHDTD;
END


-----------------------------------------------------------------
-----------------------------------------------------------------
-- Run Cursor ---

declare @mahdtd nvarchar(20);
declare cur_hdtd	cursor for
		select	MA_HOPDONG_TINDUNG
		from	HOPDONG_TINDUNG;
open	cur_hdtd;
fetch next from cur_hdtd	into @mahdtd
while @@FETCH_STATUS = 0
	begin
		exec	LOP6_B19_TAOKEHOACH	@mahdtd
		fetch	next from cur_hdtd	into @mahdtd
	end
close		cur_hdtd;
deallocate	cur_hdtd;